config/routes.rb
Rails.application.routes.draw do
  resources :custom_field_values
  resources :custom_fields
  resources :contacts

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
    get "/", :to => "users/sessions#create"
  end

  authenticated :user do
    root 'contacts#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#create"
    end
  end

end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { scope: [:user_id] }
  has_one :user
  has_many :custom_field_values, dependent: :destroy
end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  before_action :set_custom_field, only: [:show, :edit, :update, :destroy]

  # GET /custom_fields
  # GET /custom_fields.json
  def index
    @custom_fields = CustomField.where(user_id: current_user.id)
  end

  # GET /custom_fields/1
  # GET /custom_fields/1.json
  def show
  end

  # GET /custom_fields/new
  def new
    @custom_field = CustomField.new
  end

  # GET /custom_fields/1/edit
  def edit
  end

  # POST /custom_fields
  # POST /custom_fields.json
  def create
    @custom_field = CustomField.new(custom_field_params)

    respond_to do |format|
      if @custom_field.save
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully created.' }
        format.json { render :show, status: :created, location: @custom_field }
      else
        format.html { render :new }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_fields/1
  # PATCH/PUT /custom_fields/1.json
  def update
    respond_to do |format|
      if @custom_field.update(custom_field_params)
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_field }
      else
        format.html { render :edit }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_fields/1
  # DELETE /custom_fields/1.json
  def destroy
    @custom_field.destroy
    respond_to do |format|
      format.html { redirect_to custom_fields_url, notice: 'Custom field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_field
      @custom_field = CustomField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_field_params
      params.require(:custom_field).permit(:custom_field_type, :name, :description, :default).merge(user_id: current_user.id)
    end
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
  def custom_field_type_name(cf)
    case cf.custom_field_type
      when 0
        "Text Field"
      when 1
        "Text Area"
      else 2
        "Combo Box"
      end
  end
end

app/views/custom_fields/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@custom_field) do |f| %>
      <% if @custom_field.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@custom_field.errors.count, "error") %> prohibited this custom_field from being saved:</h2>

          <ul>
          <% @custom_field.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.select :custom_field_type, options_for_select([['Text', 0], ['Text Area', 1], ['Combo Box', 2]], @custom_field.custom_field_type), class: "form-control" %>
      </div>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :default %><br>
        <%= f.text_area :default, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>
    

app/views/custom_fields/edit.html.erb
<h1>Editing Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom_field %> |
<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/index.html.erb
<h1>Listing Custom Fields</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Custom field type</th>
      <th>Name</th>
      <th>Description</th>
      <th>Default</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_fields.each do |custom_field| %>
      <tr>
        <td><%= custom_field_type_name(custom_field) %></td>
        <td><%= custom_field.name %></td>
        <td><%= custom_field.description %></td>
        <td><%= custom_field.default %></td>
        <td><%= link_to 'Show', custom_field %></td>
        <td><%= link_to 'Edit', edit_custom_field_path(custom_field) %></td>
        <td><%= link_to 'Destroy', custom_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom field', new_custom_field_path %>

app/views/custom_fields/new.html.erb
<h1>New Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <p>
      <strong>Custom field type:</strong>
      <%= @custom_field.custom_field_type %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @custom_field.name %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @custom_field.description %>
    </p>

    <p>
      <strong>Default:</strong>
      <%= @custom_field.default %>
    </p>

    <%= link_to 'Edit', edit_custom_field_path(@custom_field) %> |
    <%= link_to 'Back', custom_fields_path %>
  </div>
</div>