config/routes.rb
Rails.application.routes.draw do
  resources :custom_field_values
  resources :custom_fields
  resources :contacts

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
    get "/", :to => "users/sessions#create"
  end

  authenticated :user do
    root 'contacts#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "users/sessions#create"
    end
  end

end

app/models/custom_field_value.rb
class CustomFieldValue < ActiveRecord::Base
  belongs_to :contact
  belongs_to :custom_field
end

app/controllers/custom_field_values_controller.rb
class CustomFieldValuesController < ApplicationController
  before_action :set_custom_field_value, only: [:show, :edit, :update, :destroy]

  # GET /custom_field_values
  # GET /custom_field_values.json
  def index
    @custom_field_values = CustomFieldValue.all
  end

  # GET /custom_field_values/1
  # GET /custom_field_values/1.json
  def show
  end

  # GET /custom_field_values/new
  def new
    @custom_field_value = CustomFieldValue.new
  end

  # GET /custom_field_values/1/edit
  def edit
  end

  # POST /custom_field_values
  # POST /custom_field_values.json
  def create
    @custom_field_value = CustomFieldValue.new(custom_field_value_params)

    respond_to do |format|
      if @custom_field_value.save
        format.html { redirect_to @custom_field_value, notice: 'Custom field value was successfully created.' }
        format.json { render :show, status: :created, location: @custom_field_value }
      else
        format.html { render :new }
        format.json { render json: @custom_field_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_field_values/1
  # PATCH/PUT /custom_field_values/1.json
  def update
    respond_to do |format|
      if @custom_field_value.update(custom_field_value_params)
        format.html { redirect_to @custom_field_value, notice: 'Custom field value was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_field_value }
      else
        format.html { render :edit }
        format.json { render json: @custom_field_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_field_values/1
  # DELETE /custom_field_values/1.json
  def destroy
    @custom_field_value.destroy
    respond_to do |format|
      format.html { redirect_to custom_field_values_url, notice: 'Custom field value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_field_value
      @custom_field_value = CustomFieldValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_field_value_params
      params.require(:custom_field_value).permit(:contact_id, :custom_field_id, :value)
    end
end

app/helpers/custom_field_values_helper.rb
module CustomFieldValuesHelper
end

app/views/custom_field_values/_form.html.erb
<%= form_for(@custom_field_value) do |f| %>
  <% if @custom_field_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_field_value.errors.count, "error") %> prohibited this custom_field_value from being saved:</h2>

      <ul>
      <% @custom_field_value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.text_field :contact_id %>
  </div>
  <div class="field">
    <%= f.label :custom_field_id %><br>
    <%= f.text_field :custom_field_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_field_values/edit.html.erb
<h1>Editing Custom Field Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom_field_value %> |
<%= link_to 'Back', custom_field_values_path %>

app/views/custom_field_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Custom Field Values</h1>

<table>
  <thead>
    <tr>
      <th>Contact</th>
      <th>Custom field</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_field_values.each do |custom_field_value| %>
      <tr>
        <td><%= custom_field_value.contact %></td>
        <td><%= custom_field_value.custom_field %></td>
        <td><%= custom_field_value.value %></td>
        <td><%= link_to 'Show', custom_field_value %></td>
        <td><%= link_to 'Edit', edit_custom_field_value_path(custom_field_value) %></td>
        <td><%= link_to 'Destroy', custom_field_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom field value', new_custom_field_value_path %>

app/views/custom_field_values/new.html.erb
<h1>New Custom Field Value</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_field_values_path %>

app/views/custom_field_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact:</strong>
  <%= @custom_field_value.contact %>
</p>

<p>
  <strong>Custom field:</strong>
  <%= @custom_field_value.custom_field %>
</p>

<p>
  <strong>Value:</strong>
  <%= @custom_field_value.value %>
</p>

<%= link_to 'Edit', edit_custom_field_value_path(@custom_field_value) %> |
<%= link_to 'Back', custom_field_values_path %>